package ru.graduatework.error;

public enum Code {
    UNAUTHORIZED,
    USER_DUPLICATE_EMAIL,
    USER_NOT_FOUND,
    REQUEST_VALIDATION_ERROR,
    NICKNAME_BUSY,
    INTERNAL_SERVER_ERROR,
    AUTHORIZATION_ERROR,
    MISSING_REQUEST_HEADER,
    NOT_READABLE,
    SUBSCRIPTION_LOGIC_ERROR,
    PUBLISHER_NOT_FOUND,
    COMMENT_NOT_FOUND,
    ALREADY_SUBSCRIBED,
    ARGUMENT_TYPE_MISMATCH,
    NOT_SUPPORTED,
    NOT_YOUR_COMMENT,
    NOT_BLOCK_YOURSELF,
    BLOCKED
}
